- name: add propertiary graphic drivers
  become: yes
  apt_repository: state=present repo='ppa:graphics-drivers/ppa'

- name: add nvidia drivers
  become: yes
  apt: name=nvidia-current state=installed update_cache=yes

- name: remove boot splash
  become: yes
  copy: src=grub dest=/etc/default/grub

- name: update grub
  become: yes
  shell: update-grub