- name: install stuff
  become: yes
  apt:  name={{item}} state=installed update_cache=yes
  with_items:
      - git
      - zsh
      - texlive-full
      - vim
      - haskell-platform
      - conky
