        - name: add spotify key
          become: yes
          apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id='BBEBDCB318AD50EC6865090613B00F1FD2C19886'

        - name: add spotify repo
          become: yes
          apt_repository: state=present repo='deb http://repository.spotify.com stable non-free'

        - name: install spotify
          become: yes
          apt: name=spotify-client state=installed update_cache=yes
