        - name: install hack fonts
          become: yes
          apt:  name={{item}} state=installed update_cache=yes
          with_items:
              - fonts-hack-otf
              - fonts-hack-ttf
