- name: install i3
  apt: name=i3 state=installed update_cache=yes

- name: add i3 conf
  copy: src=i3config dest={{ ansible_env.HOME }}/.i3/config
  
- name: add i3status.conf
  copy: src=i3status.conf dest={{ ansible_env.HOME }}/.i3status.conf

- name: install compton
  apt: name=compton state=installed update_cache=yes

- name: add compton config
  copy: src=compton.conf dest={{ ansible_env.HOME }}/.config/compton.conf